server:
  port: 8080

spring:
  application:
    name: backend
    devtools:
      restart:
        enabled: false
        pool-interval: 3s
        quiet-period: 1s
      main:
        banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5431/fueldistro_db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          default_schema: public
    show-sql: true
#spring:
#  application:
#    name: project
#  datasource:
#    password: admin
#    url: jdbc:postgresql://localhost:5431/fueldistro_db
#    username: postgres
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        default_schema: public
#    show-sql: true